"{namespace}.raw_{name}":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/01_raw/{namespace}/{name}.parquet
  credentials: dev_s3

"{namespace}.pre_{name}":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/02_intermediate/{namespace}/{name}.parquet
  credentials: dev_s3

"{namespace}.audience":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/03_primary/{namespace}/audience.parquet
  credentials: dev_s3

"{namespace}.spine":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/04_feature/{namespace}/spine.parquet
  credentials: dev_s3

"{namespace}.feature_{name}":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/04_feature/{namespace}/{name}.parquet
  credentials: dev_s3

"{namespace}.abt":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/05_model_input/{namespace}/abt.parquet
  credentials: dev_s3

"{namespace}.{name}_train":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/05_model_input/{namespace}/{name}_train.parquet
  credentials: dev_s3

"{namespace}.{name}_test_oot":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/05_model_input/{namespace}/{name}_test_oot.parquet
  credentials: dev_s3

"{namespace}.features_set":
  type: json.JSONDataset
  filepath: s3://olist-project-data/data/05_model_input/{namespace}/features_set.json
  credentials: dev_s3

"{namespace}.best_hyperparameters":
  type: json.JSONDataset
  filepath: s3://olist-project-data/data/05_model_input/{namespace}/best_hyperparameters.json
  credentials: dev_s3

"{namespace}.ratings_limits":
  type: json.JSONDataset
  filepath: s3://olist-project-data/data/05_model_input/{namespace}/ratings_limits.json
  credentials: dev_s3

"{namespace}.custom_lgbm_model":
  type: pickle.PickleDataset
  filepath: s3://olist-project-data/data/06_models/{namespace}/custom_lgbm_model.pkl
  credentials: dev_s3

"{namespace}.output":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/07_model_output/{namespace}/output.parquet
  credentials: dev_s3

#############################################################################################################
########################################    MONITORING   ####################################################
#############################################################################################################

"{namespace}.scored_history_partitioned":
  type: partitions.PartitionedDataset
  dataset: pandas.ParquetDataset
  path: s3://olist-project-data/data/08_reporting/{namespace}/scored_history_partitioned.parquet
  credentials: dev_s3

"{namespace}.target_history_partitioned":
  type: partitions.PartitionedDataset
  dataset: pandas.ParquetDataset
  path: s3://olist-project-data/data/08_reporting/{namespace}/target_history_partitioned.parquet
  credentials: dev_s3

"{namespace}.scored_history":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/scored_history.parquet
  credentials: dev_s3

"{namespace}.target_history":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/target_history.parquet
  credentials: dev_s3

"{namespace}.metrics_by_month":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/metrics_by_month.parquet
  credentials: dev_s3

"{namespace}.metrics_by_period":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/metrics_by_period.parquet
  credentials: dev_s3

"{namespace}.rating_metrics_by_month":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/rating_metrics_by_month.parquet
  credentials: dev_s3

"{namespace}.rating_metrics_by_period":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/rating_metrics_by_period.parquet
  credentials: dev_s3

"{namespace}.metrics_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/metrics_plot.html
  credentials: dev_s3

"{namespace}.rating_metrics_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/rating_metrics_plot.html
  credentials: dev_s3

"{namespace}.feature_metrics_by_month":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/feature_metrics_by_month.parquet
  credentials: dev_s3

"{namespace}.feature_metrics_by_period":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/feature_metrics_by_period.parquet
  credentials: dev_s3

"{namespace}.feature_metrics_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/feature_metrics_plot.html
  credentials: dev_s3

"{namespace}.features_iv_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/performance_monitoring/features_iv_plot.html
  credentials: dev_s3

"{namespace}.customers_volume_by_month":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/customers_volume_by_month.parquet
  credentials: dev_s3

"{namespace}.customers_volume_by_month_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/customers_volume_by_month_plot.html
  credentials: dev_s3

"{namespace}.ratings_volume_by_month":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/ratings_volume_by_month.parquet
  credentials: dev_s3

"{namespace}.ratings_volume_by_month_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/ratings_volume_by_month_plot.html
  credentials: dev_s3

"{namespace}.migration_matrix_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/migration_matrix_plot.html
  credentials: dev_s3

"{namespace}.features_groups_volume_by_month":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/features_groups_volume_by_month.parquet
  credentials: dev_s3

"{namespace}.features_statistics_by_month":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/features_statistics_by_month.parquet
  credentials: dev_s3

"{namespace}.features_statistics_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/features_statistics_plot.html
  credentials: dev_s3

"{namespace}.features_psi_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/prediction_monitoring/features_psi_plot.html
  credentials: dev_s3

"{namespace}.shap_values":
  type: pandas.ParquetDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/shap_monitoring/shap_values.parquet
  credentials: dev_s3

"{namespace}.shap_summary_plot":
  type: matplotlib.MatplotlibWriter
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/shap_monitoring/shap_summary_plot.png
  credentials: dev_s3

"{namespace}.shap_feature_importance_plot":
  type: plotly.HTMLDataset
  filepath: s3://olist-project-data/data/08_reporting/{namespace}/shap_monitoring/shap_feature_importance_plot.html
  credentials: dev_s3